name: "Rerender feedstock"
description: "Rerender a conda-smithy feedstock"
author: "Geoffrey Garrett"
inputs:
  workflow_github_token:
    description: |
      The GitHub token, with workflow permissions, to modify the feedstock.
    required: true
  feedstock_repository:
    description: |
      The feedstock repository to rerender.
      {owner}/{repo}, optionally {owner}/{repo}@branch
    required: true
  feedstock_branch:
    description: |
      The feedstock branch to rerender.
    required: false
    default: master
outputs:
  result_code:
    description: |
      The result code of the rerender.
      0 = success, 1 = failure
    value: ${{ steps.run-url-step.outputs.run_url }}
  run_url:
    description: |
      The URL of the run of the action.
      This can be used to inspect the log.
    value: ${{ steps.run-url-step.outputs.run_url }}

runs:
  using: "composite"
  steps:
   - uses: actions/checkout@v2
   - name: Set up Python 3.8
     uses: actions/setup-python@v2
     with:
       python-version: 3.8
   - uses: s-weigand/setup-conda@v1
     with:
       activate-conda: true
   - name: Update conda
     shell: bash
     run: |
       conda update conda
   - name: Install conda-smithy
     shell: bash
     run: |
       conda install -n root -c conda-forge conda-smithy
   - id: checkout_feedstock
     uses: actions/checkout@v2
     with:
       repository: ${{ inputs.feedstock_repository }}
       token: ${{ inputs.workflow_github_token }}
       path: feedstock
   - name: Rerender feedstock
     shell: bash
     run: |
       ls -a
       cd ${GITHUB_WORKSPACE}/feedstock
       ls -a
       git config user.name "${GITHUB_ACTOR}"
       git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
       conda smithy rerender -c auto
       git push --all -f https://${{ inputs.workflow_github_token }}@github.com/${{ inputs.feedstock_repository }}.git
   - id: run-url-step
     run: echo "::set-output name=run_url::${{ github.server_url }}/${{ github.repository }}/${{ github.run_id }}"
     shell: bash
   - id: exit-code-step
     run: |
       if [[ $? -eq 0 ]]; then
         echo "::set-output name=result_code::0"
       else
         echo "::set-output name=result_code::1"
       fi
     shell: bash